@startuml

title __P02_CELUE's Class Diagram__\n

  namespace com.baoge.designpattern {
    namespace xingweixing {
      namespace p02_celue {
        class com.baoge.designpattern.xingweixing.p02_celue.BusCalculateStrategy {
            + calculatePrice()
        }
      }
    }
  }
  

  namespace com.baoge.designpattern {
    namespace xingweixing {
      namespace p02_celue {
        interface com.baoge.designpattern.xingweixing.p02_celue.CalculateStrategy {
            {abstract} + calculatePrice()
        }
      }
    }
  }
  

  namespace com.baoge.designpattern {
    namespace xingweixing {
      namespace p02_celue {
        class com.baoge.designpattern.xingweixing.p02_celue.Client {
            {static} + main()
        }
      }
    }
  }
  

  namespace com.baoge.designpattern {
    namespace xingweixing {
      namespace p02_celue {
        class com.baoge.designpattern.xingweixing.p02_celue.TaxiCalculateStrategy {
            + calculatePrice()
        }
      }
    }
  }
  

  namespace com.baoge.designpattern {
    namespace xingweixing {
      namespace p02_celue {
        class com.baoge.designpattern.xingweixing.p02_celue.TranficCalculator {
            + calculate()
            + setStrategy()
        }
      }
    }
  }
  

  com.baoge.designpattern.xingweixing.p02_celue.BusCalculateStrategy .up.|> com.baoge.designpattern.xingweixing.p02_celue.CalculateStrategy
  com.baoge.designpattern.xingweixing.p02_celue.TaxiCalculateStrategy .up.|> com.baoge.designpattern.xingweixing.p02_celue.CalculateStrategy
  com.baoge.designpattern.xingweixing.p02_celue.TranficCalculator o-- com.baoge.designpattern.xingweixing.p02_celue.CalculateStrategy : strategy


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
