@startuml

title __V1's Class Diagram__\n

  namespace com.baoge.designpattern {
    namespace chuangjianxing {
      namespace p02_gongchang.v1 {
        abstract class com.baoge.designpattern.chuangjianxing.p02_gongchang.v1.AbsHumanFactory {
            {abstract} + createHuman()
        }
      }
    }
  }
  

  namespace com.baoge.designpattern {
    namespace chuangjianxing {
      namespace p02_gongchang.v1 {
        class com.baoge.designpattern.chuangjianxing.p02_gongchang.v1.Client {
            {static} + main()
        }
      }
    }
  }
  

  namespace com.baoge.designpattern {
    namespace chuangjianxing {
      namespace p02_gongchang.v1 {
        interface com.baoge.designpattern.chuangjianxing.p02_gongchang.v1.Human {
            {abstract} + getColor()
            {abstract} + talk()
        }
      }
    }
  }
  

  namespace com.baoge.designpattern {
    namespace chuangjianxing {
      namespace p02_gongchang.v1 {
        class com.baoge.designpattern.chuangjianxing.p02_gongchang.v1.HumanFactory {
            + createHuman()
        }
      }
    }
  }
  

  namespace com.baoge.designpattern {
    namespace chuangjianxing {
      namespace p02_gongchang.v1 {
        class com.baoge.designpattern.chuangjianxing.p02_gongchang.v1.WhiteHuman {
            + getColor()
            + talk()
        }
      }
    }
  }
  

  namespace com.baoge.designpattern {
    namespace chuangjianxing {
      namespace p02_gongchang.v1 {
        class com.baoge.designpattern.chuangjianxing.p02_gongchang.v1.YellowHuman {
            + getColor()
            + talk()
        }
      }
    }
  }
  

  com.baoge.designpattern.chuangjianxing.p02_gongchang.v1.HumanFactory -up-|> com.baoge.designpattern.chuangjianxing.p02_gongchang.v1.AbsHumanFactory
  com.baoge.designpattern.chuangjianxing.p02_gongchang.v1.WhiteHuman .up.|> com.baoge.designpattern.chuangjianxing.p02_gongchang.v1.Human
  com.baoge.designpattern.chuangjianxing.p02_gongchang.v1.YellowHuman .up.|> com.baoge.designpattern.chuangjianxing.p02_gongchang.v1.Human


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
