@startuml

title __P03_ZHUANGTAI's Class Diagram__\n

  namespace com.baoge.designpattern {
    namespace xingweixing {
      namespace p03_zhuangtai {
        class com.baoge.designpattern.xingweixing.p03_zhuangtai.Client {
            {static} + main()
        }
      }
    }
  }
  

  namespace com.baoge.designpattern {
    namespace xingweixing {
      namespace p03_zhuangtai {
        interface com.baoge.designpattern.xingweixing.p03_zhuangtai.PowerController {
            {abstract} + powerOff()
            {abstract} + powerOn()
        }
      }
    }
  }
  

  namespace com.baoge.designpattern {
    namespace xingweixing {
      namespace p03_zhuangtai {
        class com.baoge.designpattern.xingweixing.p03_zhuangtai.PowerOffState {
            + nextChannel()
            + turnUp()
        }
      }
    }
  }
  

  namespace com.baoge.designpattern {
    namespace xingweixing {
      namespace p03_zhuangtai {
        class com.baoge.designpattern.xingweixing.p03_zhuangtai.PowerOnState {
            + nextChannel()
            + turnUp()
        }
      }
    }
  }
  

  namespace com.baoge.designpattern {
    namespace xingweixing {
      namespace p03_zhuangtai {
        class com.baoge.designpattern.xingweixing.p03_zhuangtai.TvController {
            + getTvState()
            + nextChannel()
            + powerOff()
            + powerOn()
            + setTvState()
            + turnUp()
        }
      }
    }
  }
  

  namespace com.baoge.designpattern {
    namespace xingweixing {
      namespace p03_zhuangtai {
        class com.baoge.designpattern.xingweixing.p03_zhuangtai.TvController01 {
            {static} - POWER_OFF : int
            {static} - POWER_ON : int
            - state : int
            + nextChannel()
            + powerOff()
            + powerOn()
            + turnUp()
        }
      }
    }
  }
  

  namespace com.baoge.designpattern {
    namespace xingweixing {
      namespace p03_zhuangtai {
        interface com.baoge.designpattern.xingweixing.p03_zhuangtai.TvState {
            {abstract} + nextChannel()
            {abstract} + turnUp()
        }
      }
    }
  }
  

  com.baoge.designpattern.xingweixing.p03_zhuangtai.PowerOffState .up.|> com.baoge.designpattern.xingweixing.p03_zhuangtai.TvState
  com.baoge.designpattern.xingweixing.p03_zhuangtai.PowerOnState .up.|> com.baoge.designpattern.xingweixing.p03_zhuangtai.TvState
  com.baoge.designpattern.xingweixing.p03_zhuangtai.TvController .up.|> com.baoge.designpattern.xingweixing.p03_zhuangtai.PowerController
  com.baoge.designpattern.xingweixing.p03_zhuangtai.TvController o-- com.baoge.designpattern.xingweixing.p03_zhuangtai.TvState : tvState


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
